import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
    container: {
      fontFamily: '"Inter", sans-serif',
      backgroundColor: '#111827',
      color: '#F9FAFB',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '2rem',
      boxSizing: 'border-box',
    },
    header: {
      textAlign: 'center',
      marginBottom: '2rem',
    },
    title: {
      fontSize: '2.5rem',
      fontWeight: 700,
      color: '#fff',
      margin: '0 0 0.5rem 0',
    },
    subtitle: {
      fontSize: '1.1rem',
      color: '#9CA3AF',
      margin: 0,
    },
    main: {
      width: '100%',
      maxWidth: '700px', // Increased width for report
    },
    card: {
      backgroundColor: '#1F2937',
      borderRadius: '12px',
      padding: '2rem',
      border: '1px solid #374151',
      display: 'flex',
      flexDirection: 'column',
    },
    cardTitle: {
        fontSize: '1.5rem',
        fontWeight: 600,
        marginTop: 0,
        marginBottom: '1.5rem',
        color: '#fff',
    },
    formGroup: {
      marginBottom: '1.5rem',
    },
    label: {
      display: 'block',
      marginBottom: '0.5rem',
      fontSize: '0.9rem',
      fontWeight: 500,
      color: '#D1D5DB',
    },
    input: {
      width: '100%',
      padding: '0.75rem',
      backgroundColor: '#374151',
      border: '1px solid #4B5563',
      borderRadius: '8px',
      color: '#F9FAFB',
      fontSize: '1rem',
      boxSizing: 'border-box',
    },
    textarea: {
      width: '100%',
      padding: '0.75rem',
      backgroundColor: '#374151',
      border: '1px solid #4B5563',
      borderRadius: '8px',
      color: '#F9FAFB',
      fontSize: '1rem',
      fontFamily: '"Inter", sans-serif',
      resize: 'vertical',
      boxSizing: 'border-box',
    },
    fileInputContainer: {
        position: 'relative',
    },
    fileInput: {
        position: 'absolute',
        width: '1px',
        height: '1px',
        padding: 0,
        margin: '-1px',
        overflow: 'hidden',
        clip: 'rect(0, 0, 0, 0)',
        border: 0,
    },
    fileInputLabel: {
        display: 'block',
        padding: '0.75rem',
        backgroundColor: '#374151',
        border: '1px dashed #4B5563',
        borderRadius: '8px',
        color: '#9CA3AF',
        fontSize: '1rem',
        textAlign: 'center',
        cursor: 'pointer',
    },
    button: {
      width: '100%',
      padding: '0.875rem',
      backgroundColor: '#3B82F6',
      border: 'none',
      borderRadius: '8px',
      color: '#fff',
      fontSize: '1rem',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'background-color 0.2s',
    },
    buttonDisabled: {
      backgroundColor: '#4B5563',
      cursor: 'not-allowed',
      opacity: 0.7,
    },
    spinnerContainer: {
        textAlign: 'center',
        padding: '3rem',
    },
    spinner: {
        display: 'inline-block',
        width: '50px',
        height: '50px',
        border: '3px solid rgba(255,255,255,.3)',
        borderRadius: '50%',
        borderTopColor: '#fff',
        animation: 'spin 1s ease-in-out infinite',
        marginBottom: '1rem',
    },
    verificationText: {
        lineHeight: 1.6,
        color: '#D1D5DB',
        backgroundColor: '#374151',
        padding: '1rem',
        borderRadius: '8px',
        marginBottom: '2rem',
    },
    buttonGroup: {
        display: 'flex',
        gap: '1rem',
    },
    secondaryButton: {
        backgroundColor: '#4B5563',
    },
    errorContainer: {
        backgroundColor: '#4B0A0A',
        border: '1px solid #991B1B',
        color: '#FCA5A5',
        borderRadius: '8px',
        padding: '1.5rem',
        textAlign: 'center',
    },
    chatContainer: {
      flexGrow: 1,
      overflowY: 'auto',
      marginBottom: '1rem',
      display: 'flex',
      flexDirection: 'column',
      gap: '1rem',
      maxHeight: '60vh',
      paddingRight: '10px',
    },
    assistantMessage: {
      alignSelf: 'flex-start',
      backgroundColor: '#374151',
      borderRadius: '12px 12px 12px 0',
      maxWidth: '80%',
      padding: '0.75rem 1rem',
    },
    userMessage: {
      alignSelf: 'flex-end',
      backgroundColor: '#3B82F6',
      borderRadius: '12px 12px 0 12px',
      maxWidth: '80%',
      padding: '0.75rem 1rem',
    },
    messageContent: {
        margin: 0,
        lineHeight: 1.5,
        whiteSpace: 'pre-wrap',
    },
    typingIndicator: {
      display: 'flex',
      alignItems: 'center',
      padding: '10px 0',
    },
    typingIndicatorSpan: {
      height: '8px',
      width: '8px',
      backgroundColor: '#9CA3AF',
      borderRadius: '50%',
      display: 'inline-block',
      margin: '0 2px',
      animation: 'bob 1.4s infinite ease-in-out both',
    },
    chatForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
        marginTop: 'auto',
    },
    chatTextarea: {
        width: '100%',
        padding: '0.75rem',
        backgroundColor: '#374151',
        border: '1px solid #4B5563',
        borderRadius: '8px',
        color: '#F9FAFB',
        fontSize: '1rem',
        fontFamily: '"Inter", sans-serif',
        resize: 'none',
        boxSizing: 'border-box',
    },
    // Report Styles
    reportSectionTitle: {
        fontSize: '1.2rem',
        fontWeight: 600,
        color: '#E5E7EB',
        marginTop: '2.5rem',
        marginBottom: '1rem',
        borderBottom: '1px solid #374151',
        paddingBottom: '0.5rem',
    },
    overallScoreSection: {
        display: 'flex',
        alignItems: 'center',
        gap: '2rem',
        marginBottom: '1rem',
        backgroundColor: '#374151',
        padding: '1.5rem',
        borderRadius: '8px',
    },
    scoreCircle: {
        width: '100px',
        height: '100px',
        borderRadius: '50%',
        border: '6px solid',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    scoreCircleNumber: {
        fontSize: '2.5rem',
        fontWeight: 'bold',
        lineHeight: 1,
    },
    scoreCircleText: {
        fontSize: '0.8rem',
        color: '#9CA3AF',
    },
    overallSummary: {
        margin: 0,
        lineHeight: 1.6,
        color: '#D1D5DB',
    },
    scoringMatrix: {
        display: 'grid',
        gap: '1rem',
    },
    scoreBarContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
    },
    scoreBarLabel: {
        width: '120px',
        textAlign: 'right',
        fontSize: '0.9rem',
        color: '#D1D5DB',
    },
    scoreBarBackground: {
        flex: 1,
        height: '12px',
        backgroundColor: '#374151',
        borderRadius: '6px',
        overflow: 'hidden',
    },
    scoreBarFill: {
        height: '100%',
        borderRadius: '6px',
        transition: 'width 0.5s ease-out',
    },
    scoreBarValue: {
        width: '60px',
        fontSize: '0.9rem',
        fontWeight: 500,
    },
    accordion: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
    },
    accordionItem: {
        border: '1px solid #374151',
        borderRadius: '8px',
        overflow: 'hidden',
    },
    accordionHeader: {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '1rem',
        backgroundColor: '#374151',
        border: 'none',
        color: '#F9FAFB',
        fontSize: '1rem',
        fontWeight: 500,
        cursor: 'pointer',
        textAlign: 'left',
    },
    accordionContent: {
        padding: '1rem',
        backgroundColor: '#1F2937',
        lineHeight: 1.6,
        fontSize: '0.95rem',
        color: '#D1D5DB',
    },
    recommendationsList: {
        listStyle: 'disc',
        paddingLeft: '1.5rem',
        lineHeight: 1.7,
        color: '#D1D5DB',
    },
};
